[build]
  # Build command for production
  command = "npm run build && npm run build-storybook && xcopy \"storybook-static\\*\" \"public\\storybook\\\" /E /I /Y"
  
  # Directory containing the built files
  publish = "dist"
  
  # Base directory for the project (if needed)
  # base = ""

[build.environment]
  # Set Node.js version
  NODE_VERSION = "18"

# Redirect rules for SPA (Single Page Application)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Special redirect for Storybook
[[redirects]]
  from = "/storybook"
  to = "/storybook/index.html"
  status = 200

[[redirects]]
  from = "/storybook/"
  to = "/storybook/index.html"
  status = 200

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache CSS and JS files
[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache Storybook assets
[[headers]]
  for = "/storybook/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
