[build]
  # Build command for production - builds both app and Storybook
  command = "npm run build:full || npm run build"
  
  # Directory containing the built files
  publish = "dist"
  
  # Base directory for the project (if needed)
  # base = ""

[build.environment]
  # Set Node.js version
  NODE_VERSION = "18"

# Redirect rules for SPA (Single Page Application)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Special redirect for Storybook
[[redirects]]
  from = "/storybook"
  to = "/storybook/index.html"
  status = 200

[[redirects]]
  from = "/storybook/"
  to = "/storybook/index.html"
  status = 200

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Specific override for Storybook to ensure frame compatibility
[[headers]]
  for = "/storybook"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "/storybook/"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache CSS and JS files
[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache Storybook assets
[[headers]]
  for = "/storybook/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    X-Frame-Options = "ALLOWALL"
    X-Content-Type-Options = "nosniff"
